### PR TITLE
Added data sanitization for extra security

### PR DESCRIPTION
**Pull request by kaldenswart**

### CODE REVIEW

**Comment by mskian** [comment]
While Posting Data got this Error

```
{"error":true,"message":"Some error occurred"}
Warning: preg_replace() expects at least 3 parameters, 2 given in /opt/lampp/htdocs/emails/Data.php on line 78
```

**Comment by mskian** [comment]
Hey I replace
```
$data = preg_replace("/[^a-zA-Z0-9 \/{}[]:._~\-!@#\$%\^&\*áàâãªäÁÀÂÃÄÍÌÎÏíìîïéèêëÉÈÊËóòôõºöÓÒÔÕÖúùûüÚÙÛÜçÇñÑ]+/", $data); 
```


with


```
$data = preg_replace("/[^a-zA-Z0-9\s]/", "", $data);
```

 it's working well

```
   /**
     * Returns an alpha-numeric advanced character sanitized string;
     *
     * @param string $data
     * @return string
     */
    public static function clean_advanced($data){
        $data = preg_replace("/[^a-zA-Z0-9\s]/", "", $data);
        return $data;
    }
```

**Comment by mskian** [comment]
Thanks for your Contribution :100: 

I added `data sanitization` Functions :smile:  (I made Some Modification)

Work Perfectly Now :100: 

`Data.php`

```
<?php

class Data {

    /**
     * Returns a sanatized email;
     *
     * @param string $data
     * @return string
     */
    public static function clean_email($data) {
        $data = preg_replace("/[^a-zA-Z0-9-@.]/", "", $data);
        return $data;
    }

    /**
     * Strip all characters but letters, numbers, and whitespace;
     *
     * @param string $data
     * @return string
     */
    public static function clean_name($data){
        $data = preg_replace("/[^a-zA-Z0-9\s]/", "", $data);
        return $data;
    }
}
```

**Comment by kaldenswart** [comment]
No problem. áàâãªäÁÀÂÃÄÍÌÎÏíìîïéèêëÉÈÊËóòôõºöÓÒÔÕÖúùûüÚÙÛÜçÇñÑ is just extra for people with special characters in their name.
As for the error saying it needs 3 parameters I forgot the ,"" as the second parameter.
Best of luck :+1:

**Pull request closed without merging**
